STJr/SRB2

src/i_tcp.c

Fix IPv4 connectivity when IPv6 is enabled

---

src/doomdef.h

Just some clean-up in doomdef.h, nothing important or majorly game-breaking really. It's all stuff that apparently hasn't been used by the game itself in many years by now.
...
inb4 I find something else obsolete to kill later and make monster misc branch no. 3

Monster misc 2

---

src/dehacked.c
src/f_finale.h
src/f_wipe.c
src/p_setup.c

literally a straight cherry-pick of the old repository, this is a very simple change after all.

BACKPORT: special stage fade

---

src/g_game.c
src/lua_hook.h
src/lua_hooklib.c
src/p_mobj.c

I don't know how I did this but I did. Something about staring at code from 3AM till 5AM...
Here's a test script too:
```
addHook("PlayerSpawn", function(player) 
player.health = 99; 
return true; 
end)
```

Add PlayerSpawn hook to Lua

---

src/p_enemy.c

Fixes an issue with A_ChangeAngleAbsolute reported on the [MB]( https://mb.srb2.org/showthread.php?t=41236)

Changeangle hotfix

---

src/p_floor.c
src/p_map.c
src/p_mobj.c
src/p_spec.c
src/p_user.c
src/r_defs.h

MOM GET THE CAMERA
look at commit 0b920ee2492566d245c93f7a624418b6896e9080 and tell me that is not a thing of beauty (i tested it in Pipe Towers and DSZ2)
okay this merge request description is garbage, i just wanted to make it before i fell asleep because making merge requests long after branch creation isn't fun
i'll do more tomorrow and rewrite this entirely as a PROPER writeup i just wanted to drop this bombshell here before i sleebed

Sectorlist traversal

---

src/p_map.c
src/p_user.c

Does what it says on the tin. You couldn't before, now you can.
With this branch, thok barriers are now completely optional for maps with no aesthetic need for sky-topped walls. All the bugs and complications that exist with climbing right now still exist, except now there's one less issue making them suck forever and now Nev3r will be very happy.
Do I need a testing .wad? It's... not that hard to create a very small map and go nuts with Knuckles in it. I have one, but uploading it to the ftp almost feels insulting.

Climbing on one-sided linedefs

---

src/blua/lvm.c
src/command.c
src/d_main.h
src/dehacked.c
src/f_finale.h
src/hardware/hw_dll.h
src/hardware/hw_main.c
src/hardware/r_opengl/r_opengl.c
src/hu_stuff.h
src/p_inter.c
src/p_local.h
src/p_mobj.h
src/r_plane.h
src/r_splats.h
src/r_things.c
src/s_sound.h
src/screen.c
src/screen.h
src/sdl/i_cdmus.c
src/sdl/i_system.c
src/sdl/i_video.c
src/sdl/mixer_sound.c
src/st_stuff.h
src/tables.h

NULL checks
building without BLUA support
functions that do not depend on outside vars should be tagged with "const", AKA, FUNCMATH

Build modes

---

src/p_map.c
src/p_mobj.c

Why the fuck did I make this a player conditional in the first place holy shit

Fix non-player objects having busted step-up/down on slopes

---

src/p_map.c
src/p_maputl.c
src/p_maputl.h

Fixes currently included in this branch:
* A fix for a specific crash encountered in a SUGOI map (sound familiar?) caused by bouncing off a wall adjacent to a slope
Planned fixes to go in later (if we have time):
* A fix for this bug: https://mb.srb2.org/showthread.php?t=41462 seems like it shouldn't be too complicated to fix at a glance

Wall collision fixes

---

src/g_game.c
src/m_menu.c

Limit damage from http://mb.srb2.org/showthread.php?t=41847, basically.
Also fixed the message popup background because why not

Record Attack hotfix

---

src/doomdef.h
src/i_tcp.c

Also disable UPnP support on NONET builds

DIsable NetPlay on DirectDraw builds

---

src/console.c
src/hu_stuff.c
src/hu_stuff.h

Revert "Chat and console improvements"

---

src/android/i_system.c
src/console.c
src/console.h
src/d_main.c
src/djgppdos/i_system.c
src/doomdef.h
src/dummy/i_system.c
src/hu_stuff.c
src/i_system.h
src/m_menu.c
src/nds/i_system.c
src/p_setup.c
src/sdl/i_system.c
src/sdl/ogl_sdl.h
src/sdl/sdlmain.h
src/sdl12/i_system.c
src/v_video.c
src/v_video.h
src/win32/win_sys.c
src/win32ce/win_sys.c

* Unused console backgrounds no longer take up memory
* Input cursor can now move left and right
* Support for selections (Shift-arrow keys, CTRL-A, etc)
* Clipboard support (CTRL-C to copy, CTRL-V to paste, CTRL-X to cut)
* Fixed handling of simultaneous modifier key presses
https://dl.dropboxusercontent.com/u/3518218/21/console.gif
None of this affects chat yet, that's not part of the console. I'll look at it later.

Console improvements

---

src/sdl/i_video.c

Made some code look a bit neater, removed the need for some SDL2STUBs Fury placed, vid_info console command actually kind of has a use again, etc

SDL2 i_video.c code cleanup

---

src/p_user.c

Makes rope hangs and zoom tubes suck less. Specifically, they handle corners (and vertical height changes, ala sloped rope hangs) a LOT nicer. Ported from internal.

Smoother ropes and zoom tubes

---

src/d_netcmd.c

No switching skins mid-credits/custom cutscene in SP

---

debian/docs

readme.txt should be README.md. The debian build will fail without this change

readme.txt duplicated, also incorrect

---

src/m_fixed.h

Fix the FixedFloor, FixedTrunc, FixedCeil, and FixedRound functions.

FixedRounding hotfix

---

.circleci/config.yml
src/r_bsp.c

CircleCI support

---

src/d_netcmd.c

Fixed http://mb.srb2.org/showthread.php?t=42312.
Also, fixed being able to change your skin colour during credits/cutscenes in singleplayer.

Command-line skin selecting fix

---

src/p_mobj.c

This fixes the rock spawners' rocks not being removed if they rolled down to the ground from a slope rather than bouncing (see https://mb.srb2.org/showthread.php?t=41963)

Falling rocks fix

---

src/d_netcmd.c
src/w_wad.c
src/w_wad.h

This is a fix for this bug: https://mb.srb2.org/showthread.php?t=42279

Addfile directories fix

---

src/hardware/hw_glob.h
src/hardware/hw_main.c

OpenGL Flatsprites

---

src/sdl/i_system.c
src/sdl/i_video.c

Mostly cleanup tbh. I noticed a few things that bugged me when examining SDL's code recently, thought I might as well fix them up a bit.
These changes definitely does not affect netplay, so this can be merged to master just fine.

SDL fixes and cleanup

---

src/d_clisrv.c
src/d_netcmd.c
src/d_netfil.c

Fixes:
* Having bunch of music WADs added and then breaching the file limit(s) through joining a server with important files added. http://mb.srb2.org/showthread.php?t=42662
* Having a bunch of music WADs added, joining a server, and then breaching the file limit(s) when the server adds a file. https://mb.srb2.org/showthread.php?t=34664
* Informing the adminplayer whenever they try to send a request addfile net command but the file limit(s) are reached.
Done into next because I might as well be 100% safe, even though this could probably work on master as well.

A bunch of bugfixes about too many wads in netgames

---

src/hardware/r_opengl/r_opengl.c
src/sdl/ogl_sdl.c

Fix for this bug: https://mb.srb2.org/showthread.php?t=39882 (also reported here: https://mb.srb2.org/showthread.php?p=793077#10)
This is basically porting GZDoom's own fix for the same issue (I stumbled on a Zandronum thread about the same issue from google images, and one user mentioned GZDoom had fixed it): https://github.com/doomtech/gzdoom/commit/d31a0b77fd19dae611166265acabe666c7ab1c59

Fix for screenshots taken in OpenGL with resolution 1366x768

---

src/p_spec.c

Had to make P_MobjReadyToTrigger non-inline for this fix though, because the compiler was being stupid

Ld414 invalid sound fix

---

src/p_floor.c
src/p_user.c

Fixes the issue with Each Time reported here: https://mb.srb2.org/showthread.php?t=42818
Also fixes a separate issue with P_IsObjectOnGroundIn and intangible FOFs (where it determined that standing at the top height of them counted as being on the ground) which was also reproducable via the above bug funnily enough.

Fixes for Each Time and P_IsObjectOnGroundIn

---

src/dehacked.c

Fixes this issue: https://mb.srb2.org/showthread.php?t=42939
This isn't just a Linux issue as it turns out, it affects Windows too (so likely also Mac as well)

Fix save games for a custom mod not saving to custom home folder

---

src/command.c
src/d_clisrv.c
src/d_net.c
src/p_saveg.c

...Oh wow, I forgot I was planning to do further netcode fixes a while ago. Apparently I just made some fixes to the debugfile and added some extra debugging messages in the end though.
I'll leave this WIP until I can decide if it's worth going in as it is or not.

WIP: Netcode fixes the sequel

---

src/d_netcmd.c

See [SRB2MB: Instant Sync Failure and server freeze when you add the same mod twice through a .TXT](https://mb.srb2.org/showthread.php?t=43144) and [SRB2MB: Adding a file that was previously added would boot you from the server](https://mb.srb2.org/showthread.php?t=43048)
Basically this fix means in netgames `addfile` now checks properly if there are already too many wad files loaded (whether exceeding the available space left in the `filesneeded` array, or the hard-coded file maximum), or the file has already been uploaded. Single Player/anywhere else outside of multiplayer already has such checks via `W_LoadWadFile`, so they weren't a problem there.
This is a merge request to master since only the server should be affected by this fix.

"addfile" console command netgame fixes

---

src/p_spec.c

Backport of toaster's airbob sector fix from our internal repo.

Airbob fix backport

---

src/d_clisrv.c
src/d_netcmd.c

This should fix https://mb.srb2.org/showthread.php?t=43205
EDIT: As a bonus I've gotten -playdemo and -timedemo to work again; however, the change involves may or may not be master-safe, so I'm merging this to next instead

Fix for "playdemo" not working with custom home paths

---

src/d_netcmd.c
src/m_misc.c

Doing it into master because fuck you that's why.
Also, because it's netplay safe.

Stop leaking names via metadata.

---

src/console.c

Fixes [SRB2MB: Little console oversight](https://mb.srb2.org/showthread.php?t=43219)

Console key breakfast

---

src/d_netfil.c

This branch rewrites `findfile` from `d_netfil.c` so it'll be able to properly report in Linux and the like whether there was a file found in one of its three search paths with a bad MD5, rather than pretending it doesn't exist.
Note: Untested as of writing, but I assume it should be safe for master, since file searching is entirely local. Could be wrong though.

Rewrite of d_netfil.c's findfile

---

src/hardware/hw_main.c

(Separate L and R sprites were broken, I figured out I was a dunce, oh noey)

OpenGL: Paper Sprites: The Thousands of Bugs

---

src/d_clisrv.c

A few minor net command-related fixes.

Minor net command fixes

---

src/r_draw8.c

Apply the double-colormap ordering fix to R_DrawTiltedTranslucentSpan_8 as well.

Woops! All trans

---

src/sdl/mixer_sound.c

An attempt at fixing issue [#31](https://git.magicalgirl.moe/STJr/SRB2/issues/31), at least for sounds as of writing.

SDL Mixer fixes

---

src/android/i_cdmus.c
src/djgppdos/i_cdmus.c
src/s_sound.c
src/sdl12/i_cdmus.c
src/win32/win_cd.c
src/win32ce/win_cd.c

Because honestly, the default is way too loud.

Change default sound volume

---

src/g_game.c

Fix up them there ghosts!
* Stop orphaning their memory. They ARE PU_LEVEL, so they'll disappear eventually, but, like... it's not good memory management practice to just orphan them when you're literally never going to do anything with them ever again. Y'know?
* Make ghosts spawn properly on slopes.
No testwad needed, it should all be reasonably self-evident.

Zalloc Potter and the Death-Free Hallows

---

src/r_main.c

Fixes [SRB2MB: "homremoval" cvar disregards non-green resolutions](https://mb.srb2.org/showthread.php?t=43480)

Fix for HOM removal in non-green resolutions

---

src/i_tcp.c

As of writing this just includes some minor fixes to `i_tcp.c`, one of the files that contains SRB2's "netcode". I don't know offhand if this actually fixes anything serious netcode related, but as far as I can tell what I've done shouldn't negatively affect the netcode.
Though just in case (or if I wanted to add more), I'm making this a merge to `next` anyway.

Netcode nitpicking

---

src/p_floor.c

This fixes two issues where:
* Thwomp triggers on a spectator player
* Thwomp triggers even when its FF_EXISTS flag is unset
[Thanks Panda.!](http://mb.srb2.org/showthread.php?p=802139)

Thwomp fixes: Don't trigger on spectator; don't trigger on ~FF_EXISTS

---

src/d_clisrv.c
src/d_main.c
src/d_main.h
src/d_net.c
src/d_netcmd.h
src/doomstat.h
src/f_finale.c
src/g_game.c
src/hardware/hw_bsp.c
src/hardware/hw_main.c
src/hu_stuff.h
src/p_local.h
src/p_user.c
src/r_main.c
src/r_state.h

Just removing a bunch of unused variables/function prototypes from the source code and similarly minor stuff, nothing here should change gameplay much (if at all).
Another backport of commits I made for 2.2.

MI's unimportant code cleanup

---

src/d_netcmd.c
src/d_netcmd.h
src/s_sound.c
src/s_sound.h

Move commands and console variable into s_sound.c. Everything is the same on the user's side, and it's just purely code refactoring.

Some code cleanup.

---

src/p_mobj.c
src/p_user.c

Fixes https://mb.srb2.org/showthread.php?p=802600#post802600 and by extension https://mb.srb2.org/showthread.php?t=42918. Where post-processing visual effects won't work correctly from a remote viewpoint. 
I was given permission by Jimita to do this.

Minor remote viewpoint bugfixes.

---

src/sdl/i_system.c
src/sdl/i_video.c
src/sdl/mixer_sound.c
src/sdl12/mixer_sound.c

Adds missing copyright info to some files and updates some outdated files.

Update copyright info

---

src/r_segs.c

Some cleaning up I did a month ago, while trying to get to the bottom of one or two unexplained software renderer crashes that apparently involve FOF walls. I kind of forgot about it though, nor did I fix the crashes (yet).
Not especially urgent to merge in, but it makes the relevant code a bit easier to read in places.

FOF wall rendering fixes and cleanup

---

src/d_clisrv.c

This fixes the bug encountered in SRB2Kart where, in the in-game server list menu, the number of servers listed for a room can shrink when you refresh. If you leave the menu and then reenter, the full list reappears again. This bug I hear also applies to vanilla (not anyone can test that right now) so I'm making the fix in this repo rather than Kart's.
If you want to know details on why it happens (and you know *something* of how the netcode works), it's because the game makes connections to all servers when sending ASKINFO packets to them, ...but never closes the connections if you never hear anything back from each server (usually if they haven't forwarded your ports). At least, until you exit the menu. I've fixed this by "disconnecting" you from each server you send ASKINFO packets to; …

Disappearing servers fix

---

src/m_menu.c
src/mserv.c

Do you guys remember times when the Master Server was down, where attempting to connect to it in-game gave you messages saying you needed to update to version "25"? Well, I've hopefully fixed that and made the game give a proper message if it can't get anything back from the MS.

Master Server Update alert fix

---

src/f_finale.c

Make the credits pics darker

---

src/p_map.c

Last min cleanup

---

src/r_main.c
src/r_plane.c
src/r_plane.h

Hope you don't mind Jimita, but we really would like to have this fix for software at least, so I made a copy of it on our repo a while back.
Fixes exactly what it says in the title.

Fix glitches with flats visible when looking up/down in 1st person (software renderer fix)

---

src/m_menu.c
src/sdl/i_system.c
src/sdl/i_video.c

Attempts to fix joystick event handling in general, as well as also fixing joystick use in menus. Needs feedback and testing.

WIP: Joystick juggling

---

src/Makefile
src/hardware/hw_bsp.c

Some cleanup of `hw_bsp.c`, and also a fix for the holes popping up in 64-bit OpenGL (see [SRB2MB: \[64-bit OpenGL\] someone blew a hole in GFZ2](https://mb.srb2.org/showthread.php?t=43981))

Opengl BSP cleanup and fixes

---

src/am_map.c
src/am_map.h
src/d_main.c
src/hardware/hw_draw.c
src/hardware/hw_main.h
src/p_local.h

Levels like Arid Canyon Zone 1 and Aerial Garden Zone now display properly on the automap.

Automap fix

---

src/console.c
src/r_bsp.c
src/r_main.c
src/r_plane.c
src/r_plane.h
src/r_segs.c
src/r_splats.c
src/r_things.c
src/screen.c

This commit fixes:
* [This](https://github.com/STJr/SRB2/pull/291) fix
* Floor wobble on large resolutions such as 1920x1200.
* Polyobjects causing slime trails on FOFs around them, sometimes
* Polyobjects rendering the flat of the sector they are on twice, as if it were a shadow

Software plane fixes

---

src/p_user.c

Fix remote viewpoint cameras for real this time

---

src/lua_baselib.c
src/lua_maplib.c

*repeats "sorry" while shrinking into the form of a corn cob*

Lua: Kart textures backport (non-foolish vers)

---

src/lua_baselib.c

Desperately needed for SUGOI 3

Lua: nextmapoverride & skipstats changing outside of G_ExitLevel

---

src/lua_maplib.c

Sequel to[ !263](https://git.magicalgirl.moe/STJr/SRB2/merge_requests/263)
I apparently forgot to make ffloor_t's toppic and bottompic behave the same way as sector_t's floorpic and ceilingpic. Whoops!

Lua FOF flat names fix

---

src/d_netcmd.c
src/g_game.c
src/g_game.h
src/m_menu.c

Backport from 2.2... from memory, because I left my code access. :V 
WIP because I need to figure out a good way to tackle the joy axis config update shenanigans...

Feature: Jump/Spin axes

---

src/f_finale.c

Upon Nev3r's suggestion:
* Simon "sirjuddington" Judd -- SLADE developer
* Pascal "CodeImp" vd Heiden -- Doom Builder developer

Add sirjuddington and CodeImp to Special Thanks credits

---

src/sdl/i_video.c

Closes [#46](https://git.magicalgirl.moe/STJr/SRB2/issues/46) Where the input is not properly captured by mouse on startup.

SDL:Auto grab input

---

src/sdl/i_video.c

Fixes <https://mb.srb2.org/showthread.php?t=44110>.

Update capslock state on window re-focus

---

src/dehacked.c
src/hardware/hw_cache.c
src/hardware/hw_glob.h
src/hardware/hw_main.c
src/p_setup.c
src/p_setup.h
src/p_spec.c
src/r_data.c
src/r_data.h
src/r_draw.c
src/r_draw.h
src/r_draw8.c
src/r_plane.c
src/r_plane.h
src/screen.c

If I'm missing anything, please poke me about it @Jimita .
To anybody, feel free to test it on your own and give your feedback on the comments, it'd be appreciated.

Jimita flats

---

src/f_finale.h
src/f_wipe.c
src/g_game.c

See https://git.magicalgirl.moe/STJr/SRB2/merge_requests/962

NOWIPE fixes for colormap and title card wipes

---

src/sdl/mixer_sound.c

https://git.magicalgirl.moe/STJr/SRB2/merge_requests/990

Fix OPENMPT deprecation error, openmpt_module_ctl_set

---

src/hardware/r_opengl/r_opengl.c

https://git.magicalgirl.moe/STJr/SRB2/merge_requests/989

Strike null-pointer-arithmetic error in BUFFER_OFFSET
