src/dehacked.c
... because some things (Lua. custom header entries) move it.
https://mb.srb2.org/showthread.php?t=40580
(Technically breaks netgame compatibility for Lua-heavy mods, so in next.)
=> Make sure "word" in readlevelheader gets reset

src/p_map.c
Makes MF_PAIN check for health before damaging the player. Fixes[ issue #12](http://git.magicalgirl.moe/STJr/SRB2/issues/12)
=> Fix dead MF_PAIN objects hurting the player

src/p_inter.c, src/p_user.c
Basically you're not allowed to launch off a chain the frame you touch it anymore.
Coincidentally the changes here allow you to actually use `PF_*STASIS` in a Lua script now and have it work as you'd expect it to (it lasts for a tic).
=> Fix chain launching

src/lua_maplib.c, src/p_spec.c
This fixes rendering issues caused by changing FOF flags mid-level via Lua or linedef type 445. Everything else that toggles FF_EXISTS already had this fix it turns out.
=> Fof flag change hotfix

src/lua_hooklib.c, src/lua_script.c, src/lua_script.h
Updated NetArchiveHook to new lua_hooklib.c standards.
Fixes I_Assert failure crash due to hooks working differently in next.
=> Crashfix Lua hook_NetVars

src/dehacked.c
Pretty simple thing. Allows scripters to use VERSION, SUBVERSION, and VERSIONSTRING to check the game's version and potentially futureproof scripts. Have tested and confirmed working on my end.
=> Version constants for Lua

src/r_segs.c
The ceiling lighting linedef special (and anything else that changes ceiling lighting directly for sectors) works in software mode now.
=> Ceiling lighting fix

src/hardware/r_opengl/r_opengl.c
Screen transitions don't work in OpenGL when scr_depth is set to 8 or 16 bits. This fixes that.
=> Fix OpenGL Fademasks (Screen Transitions)

src/r_plane.c, src/r_plane.h
More portal-related fixes:
- Fixes rendering issue 4 from issue [#21](http://git.magicalgirl.moe/STJr/SRB2/issues/21) (Slope planes render with wrong height values when visportals are visible on-screen)
- Fixes sky rendering through portals, so that the sky you see through each portal is what you'd expect to see if you were actually there. Easiest way to see what I mean is through sky 22's planet, in a map with portals at 90 degrees to the other sides respectively (the example map on the wiki for ld40, for instance).
=> Fix portal and plane/sky interaction

src/g_game.c, src/p_local.h, src/p_map.c, src/p_spec.c, src/p_user.c
Changes made/bugs fixed in this branch:
- Replay camera is now controllable when climbing (https://mb.srb2.org/showthread.php?t=38668), and in waterslides
- localangle (read: the angle between you and the camera, I think) now doesn't change during demo replays in most situations, unless the player is in analog mode. Exceptions include zoomtubes and NiGHTS super
- Replay camera now doesn't act silly if the player is in analog mode (assuming you also recorded it in that mode to begin with, anyway)
=> Demo replay fixes

src/p_mobj.c, src/p_user.c
Fixes the following issues relating to playing as NiGHTS Super Sonic that apparently popped up between 2.1.14 and next (mostly due to the changes to SRB2's trig stuff it seems):
- Super Sonic drifts to the side at some angles around an axis, and is unable to go directly upwards or downwards as a result
- Drilling to the side when on the ground causes the drill sound to constantly restart
- CEZS's start not actually being on the first axis means the player is not able to go backwards along the track (because the player is not actually aligned with the track properly)
- trying to hug some walls such as the tall wall before the library section of CEZS allows Super Sonic to go through them
These fixes needs proper testing before this branch can be merged in, in case they accidentally break …
=> Nights hotfix

src/win32/Makefile.cfg
The following things are already dealt with in sdl/Makefile.cfg I'm pretty sure:
* -lSDL2_mixer is already added to SDL_LDFLAGS by default, unless NOMIXER=1 is set
* -DSDLMAIN should also be added to OPTS by default for MINGW=1 builds, unless NOSDLMAIN=1 is set
Just making this branch here on GitHub so Alam can make sure it's all fine and stuff I suppose?
=> Some SDL-related compiling tweaks

src/r_segs.c
This branch SHOULD fix the many crashes people have reported lately that all point to the software renderer. Simply put, the software renderer allowed stuff to be drawn out of the screen even though that wasn't safe, and even the existing checks to prevent that didn't work.
If you saw me worrying about the sky HOMs I discovered in AGZ earlier in the commits for this branch, don't worry - it turns out that issue already existed in 2.1.15's srb2win.exe (and probably srb2dd.exe too) anyway, the changes in this branch didn't cause them. Hopefully nothing else broke then.
=> Software crashes fix

src/p_mobj.c
Ran into an issue whilst testing out one last feature (there's always one more...) for flat_alignment_revamp. This is a backported fix.
The bug was such that if you're falling through a platform with FF_REVERSEPLATFORM and not FF_PLATFORM, you'll be pushed downwards such that your head is against the bottom of the FOF. This just checks momz is greater than zero if it has FF_REVERSEPLATFORM to make sure it's okay to set ceilingz.
No test map because this was originally done for internal. Instead, test it on the other branch's test map.
=> FF_REVERSEPLATFORM clipping

src/r_segs.c
Some other software fixes/changes I've made
* Change 1: single-sided linedef midtextures (read: not double-sided linedefs, but single-sided) now don't skew if Effect 2 is checked. Before, there wasn't any ability for software to disable skewing for them. =V
* Change 2: PolyObject back side midtextures now return to being where they should be. Had to make a hack to fix this though.
=> Some other software fixes/changes

src/p_setup.c, src/p_sight.c
Changes made in this branch so far:
* a REJECT lump of zero length (NOT to be confused with a REJECT lump of non-zero length with all-zeros, just to clarify) should no longer cause problems with netgames and otherwise. The game now checks if the lump exists, has the right name, and length is not zero - if it fails any of these, the REJECT lump is not loaded and P_CheckSight won't be allowed to use it. This means ZDBSP (no reject) should be safe(r) to use now!
* there's now a simple devmode-only message (requires "Setup" mode) if a sector is found to have no lines at all during setup. It's a far cry from the plot to I_Error the game I once had for that unsusal scenario, but such a level still works anyway so whatever.
=> Fixes and changes related to the act of setting up a level (in other words, setup fixes)

src/p_map.c, src/p_mobj.c
Whoop whoop whoop minor bugs that only get noticed due to weird experiments whoop whoop whoop
* For gas jets only: mo->standingslope is ALWAYS null. No drifting down the slope for you.
* For gas jets and fan objects: Now checks whether the player's top is below the bottom of the launcher, instead of its bottom. zdist calculation not affected, since it's signed and okay with being negative by about the height of the player.
* For all 3: mo->standingslope is NULL'd so the player isn't launched off at a wacky angle if they're standing on a slope then walk into the thing.
=> Gas jets, fan objects, springs and slopes

src/r_main.c
Fixes the issue reported in this thread: https://mb.srb2.org/showthread.php?t=41729
I dunno if this will negatively affect any existing skyboxes in SRB2's own levels, that said. I tried out THZ2 and CEZ1 with this fix at least but I forgot to compare them with how they are in 2.1.15 so _*shrugs_*
=> Skybox rendering offset fix for third person/alt view camera

src/r_draw8.c
This fixes how R_DrawTiltedSplat_8 unintentionally allows the cyan pixels to NOT be considered "transparent" if after being remapped, depending on sector brightness and/or linedef type 606 colormaps, the result of remapping is not palette index 247 (the cyan we typically turn transparent). That is, the original colors from the source flat graphic are not checked, but instead the __result__ of coloring the flat under the respective colormap is checked for "transparent" pixels. This is only a problem for the tilted splat drawing function, not the regular one for non-sloped planes with cyan-pixel-using flats.
I found out about this bug from the issues Ritz was having with sloped 255-alpha translucent FOFs using transparent flats and his custom COLORMAP lump (and later when he applied a …
=> Fix for flats with transparent pixels on slopes

src/r_segs.c
Fixes a typo introduced by merge request !75 that caused upper textures to set the wrong ceiling clipping value when not visible, allowing all sorts behind the walls to be visible. This is most noticable in GFZ2 when the inside of the tunnel section is visible
...probably a good idea to make sure this one doesn't introduce any MORE visual glitches by mistake (again, compare with 2.1.15 if possible)
=> Software crashes fix... fix

src/r_things.c
Whoops, seems I forgot about this little branch. Basically this fixes how for a character's sprites, a full sprite lump name is displayed instead of just its sprite prefix in the "R_AddSingleSpriteDef: No patches found for [sprite prefix] frame [frame character]" message (unlike when it occurs for non-character sprites), resulting in something like "R_AddSingleSpriteDef: No patches found for PLAYC2C8 frame \^" which does NOT help custom character authors at all as it just confuses them instead. (for the record, the problem would actually with the ^ frame and not the ones displayed after "PLAY")
Oh, and the same problem is also fixed for this similar message: "R_AddSingleSpriteDef: Sprite [sprite prefix] frame [frame character] is missing rotations"
=> Fix R_AddSingleSpriteDef's I_Error messages

src/r_draw8.c
This fixes a case with sloped FOFs where "upside-down" parts of such FOFs (bottom higher than top I mean), or anything close enough to that like 0-height parts of such FOFs, crash the game in the software renderer.
Hopefully this stops FuriousFox's map crashing for the time being, all seemed fine when I tested it out myself.
=> Fof slope crash fix

src/hardware/hw_main.c
This branch removes a specific hack in the OpenGL code for detecting if a plane is for the floor or ceiling of a sector. This it turns out fixes ceiling slopes in Boinciel's SUGOI map going missing. Though, It doesn't fix that other glitch with one FOF (must be unrelated).
If you want to test these fixes out properly, make sure working in-level sectors, FOFs AND also polyobjects all still work fine, sloped or not.
=> OpenGL planes fix

src/lua_hud.h, src/lua_hudlib.c, src/st_stuff.c
Does what it says on the tin.
Requested by Lat and Speedwagon, selfishly also desired because of Thokker, open and shut. If 2.1.16 is delayed, might as well get some goodwill-raising zero-effort stuff in there.
=> Allowing the disabling of Match/CTF/Miscellaneous Ringslinger HUD elements 

src/p_map.c, src/p_user.c, src/r_main.c
Fixed Knuckles being able to climb in space in OpenGL. 
To understand: look at AjustSegs(void) in hw_bsp.c. It reallocates the vetex_t pointers for lines as POLYVERTEX_T pointers, and of COURSE things are gonna get wacky when you're casting pointers.
I dunno how resilient the FLOAT_TO_FIXED solution is or whether it'll be netgame compatible (yayyy float precision loss) but it's not like our builds are netgame compatible with themselves
This merge request is into master because it's a bug that's IN master and must never reach the public because of how bad it is
=> Climbing shit 2 electric boogaloo: an adventure in how much toast hates how the ogl renderer was implemented

src/f_finale.c
Yet another fix for SUGOI, lol: apparently going from a final level's post-cutscene straight to a custom credits cutscene gets the latter stuck forever in the first scene (because the game accidentally stops the cutscene responder from realising the custom credits cutscene is running). This branch of course makes a fix for that.
=> Cutscene switch fix

src/p_mobj.c, src/st_stuff.c
One single-line fix concerning the end of NiGHTS maps. Extremely small, literally zero side effects here, the only reason I'm not committing directly to master (aside from ettiquette) is that I don't have the ability to do so.
* The NiGHTS drone had a single tic of visibility when you hit the goal, which is evident stepping frame by frame through http://gfycat.com/ComplicatedComposedAoudad (the contents of which may or may not make it into 2.2). This is no longer the case.
=> Last-minute NiGHTS exiting bugfix

src/p_map.c, src/p_mobj.c, src/p_user.c
Another slopes fix branch!
This branch currently includes a fix for:
* Knuckles gliding into a slope while in 2D mode causes him to try to "climb" on air above them, if the original non-sloped height is higher. Unfortunately he still tries to grab onto places that he can't really climb on, but at least now it's on the slope itself and not in mid-air lol. This issue is encountered in SUGOI's Retro Hill Zone, if you want to check for yourselves.
(Other fixes may or may not appear here in the near future, I haven't decided yet. Don't wait on me to get in any further fixes before merging, that said)
=> More slope fixes (aka sorry guys I made another quick SUGOI fix)

src/g_game.c
As reported: http://mb.srb2.org/showthread.php?t=38792
Turns out srb2 attempts to record demos to replay/main/[demoname].lmp, but expects demo files to be in [srb2home]/replay/main/[demoname].lmp.  Note the use of a relative path.  With Linux, if [srb2home] and the binary directory aren't the same, then demos won't be written, and if you make replay/main, then they will but SRB2 won't be able to locate them.
This fix ensures that demos are actually saved to [srb2home].  This should change nothing on Windows and fix everything on Linux.  There's also a chance it'll fix OS X.  But do note, I'm too lazy to test on Windows and I don't have access to an OS X machine to test that.
=> Fix demo recording in Linux

src/m_misc.c, src/p_spec.c
SLADE adds this character in its TEXTURES editor and makes SRB2 cry unless the lump is manually edited; this just treats it as whitespace so we don't have to think too hard about it.
Also, two I_Errors now refer to the correct lump name.
=> Treating " as whitespace in TEXTURES (and animdefs too i guess)

src/p_spec.c
What it says on the tin pretty much:
Currently included fixes:
* Pusher specials applied to FOFs did not properly account for slopes applied to the bottom plane; this probably was just a minor slipup that appeared on adding the support in the first place, I take it? (some waterfall in the last section of SUGOI's Fudge Canyon is the only place I can think of offhand where this bug is noticable)
=> Even more slope-related fixes

src/p_mobj.c
Forgot the case where == 0.
Tested by @wolfy852 in Top Down, where the bugs this caused were first discovered.
=> Fixing FF_REVERSEPLATFORM clipping fixes 

src/lua_hudlib.c
Lua now errors if you try to use negative scales with v.drawScaled, rather than crashing as it does in 2.1.16 currently. Not much else to say here.
=> v.drawScaled negative scales fix

src/p_setup.c, src/p_spec.c, src/r_data.c
New PWAD ANIMDEFS lumps can now reliably overwrite previously-defined texture and flat animations with new end lumps and speeds.
P_InitPicAnims will now be called only when wads are added, not every level load. (Possibly reducing level load time if many large ANIMDEFS lumps are used.)
=> Fix ANIMDEFS process order

src/p_map.c
* Solid objects are now no longer intangible when your z is less than the other object's.
* I originally thought the bug was limited to just solid objects on slopes (hence the branch name), and was wondering about undesired side effects - but looking at this gfy, this was a major bug that slopes made easier to expose.
* Unfixed = http://gfycat.com/BareLimitedCavy
* Fixed = http://gfycat.com/JubilantOffensiveGar
* You now properly lose your momentum when jumping at a solid object.
* The way I fixed this was a hack, but it was originally a much worse hack which resulted in very bizzare physics issues, so...
* Unfixed = http://gfycat.com/ShockingAbsoluteArthropods (also demonstrates the first bug)
* Fixed = http://gfycat.com/EmbellishedCourageousGordonsetter
=> Fixing various problems with MF_SOLID collision

src/p_mobj.c
* Before: http://i.imgur.com/gxUFElo.png
* After: http://i.imgur.com/NxsOg94.png
The problem was that MT_OVERLAY's default radius and height were never getting changed from 1*FRACUNIT, and that meant that when you spindashed, the game considered it completely below the surface of the flat you were standing on. Since you're not usually clipped on flats that don't belong to FOFs, we didn't notice this aspect of the issue sooner.
I'm also tweaking the shield stuff to make SURE it doesn't happen again, but I doubt it's strictly necessary.
=> Fixed players disappearing when spindashing whilst wearing multi-layer shields 

src/hardware/hw_main.c, src/m_cheat.c, src/p_user.c, src/r_main.c
Now works in GL by not relying on stuff which GL mutates! Thanks for the guidance, @MonsterIestyn! Tested in Steel_Titanium's Nightlight Ruins (in SUGOI), which had the perfect testbed for plenty of Knuckles issues AND is one of the first maps out to the public which eschews thok barriers altogether in some sections.
* Knuckles climbing on one sided lines is now super great and doesn't allow any space-climbing at all, OGL-exclusive OR renderer-independent. I was able to restore my earlier perfect-in-Software fix because now it also works fine in GL, too!
* The devmode TELEPORT command now actually prevents you from going outside maps which don't have thok barriers near where you were. (It only prevented you from going outside maps with thok barriers because the thok barriers bled outwards …
=> P_IsPointInSubsector fix! (Most importantly: Knuckles No Longer In Space)

src/sdl/mixer_sound.c
Due to the way SRB2 resamples sounds, the result of a division is stored into an integer value, resulting in truncation.   The truncated value, frac is something like a percent counter, counting the percent of sound samples that have played in a range.  When there are more samples than the native output rate of 44100, this truncation causes all sound samples to have played prior to the counter reaching full, and the game will attempt to play non-allocated memory, resulting in a crash.  Why this crash isn't apparent in 32-bit, I have no idea.  It may have to do with how memory is internally managed.
The fix in this pull request probably isn't "correct," but it's as correct as the last time I fixed a sound crash, which is just above in line 176.
=> Prevent resampling-related crashes on Linux 64-bit

src/console.c, src/hu_stuff.c, src/hu_stuff.h
You can now move the cursor in command prompt and chat, using left/right, ctrl+left/right, home/end, and select text with shift. Pressing ctrl is now needed to navigate to the oldest/newest lines in the console buffer.
=> Chat and console improvements

src/hardware/hw_md2.c, src/hardware/hw_md2.h
Fix for this bug: http://mb.srb2.org/showthread.php?t=42099
The model reading code didn't properly check if the model had too many vertices, so models with higher counts freely broke the game. This fix now stops that and prints an error message if that is the case.
However, it seems some models happily exceed other limits such as texcoords without problem (to my knowledge), so I've not bothered with checking those limits for now. Perhaps this could be a time to discuss if we need to change such limits again or not? Either way, one can easily uncomment my lines for checking texcoords/skins/triangles limits later if needed.
=> MD2 vertices limit check

src/hardware/hw_draw.c
This fixes the console selection highlighting being wrongly positioned and sized for OpenGL.
=> HWR_DrawFill support for V_NOSCALESTART

src/p_mobj.c
What the title says. I blame MFE_ONGROUND for being stupid, but for now I made it behave a bit better with flipped items at least.
=> Fix ceiling springs thrusting themselves down in midair on touch

src/lua_hook.h, src/lua_hooklib.c
Mobj hooks are now directly linked to the mobjtype they belong to, rather than being added in one huge generic linked list with all other hooks. MobjThinker, MobjCollide and MobjMoveCollide hooks have their own dedicated lists as they are called very often and thus need fast retrieval.
That way you can add as many hooks as you want without having terrible framerate drops in NiGHTs and other maps full of mobjs.
Also linedef executor hooks and some player hooks have their own hook lists.
=> Hook optimisation

src/d_netcmd.c, src/p_saveg.c
This fixes the first mobj thinker added/read from $$$.sav not being relinked to other objects as their target/tracer/etc properly. In particular, this fixes Brak's electric shield disappearing for anyone joining a netgame playing ERCZ (as Brak happens to be the first object added/read in this case, and Brak is the shield's target).
=> Savegame hotfix

src/m_fixed.h, src/r_defs.h, src/r_main.c, src/r_main.h
This is just removing SSNTails's old port of ZDoom's secplane code and math, from back when he attempted slopes himself. The slopes we've had since 2.1.15 however do not need these, so we can pretty much toss the code for them out now (nothing uses them anyway).
=> Remove secplanes

src/lua_maplib.c, src/p_saveg.c, src/p_setup.c, src/p_setup.h
This should fix how Lua scripts that change flats in levels, particularly to flats that don't already exist in the level, cause SRB2 to crash for anyone who joins a netgame afterwards. (I'm not sure if it's a consistent thing or not though)
Probably needs a good test to verify the issue is completely fixed before being merged in. Maybe there are other minor things I didn't account for in this fix? I don't know!
=> Flat changing hotfix

src/hardware/hw_main.c, src/p_maputl.c, src/r_data.c, src/r_data.h, src/r_defs.h, src/r_segs.c
Bugs fixed in this branch:
* upper/lower/middle textures with non-existent texture ids being capable of crashing the game. For instance, RVZ1 has colormap codes on non-colormap linedefs, which causes them to wind up with invalid texture ids because of how the game tries to interpret lower/upper textures with "#" followed by characters on normal linedefs. Fortunately these "textures" are normally not visible anyway (since they're all in control sectors) unless they are swapped with in-level textures by some crazy Lua script of some sort...
* animated single-patch textures with holes displaying garbage on first viewing (see this thread: https://mb.srb2.org/showthread.php?t=42195)
=> Some texture-related fixes

src/r_bsp.c, src/r_plane.c, src/r_plane.h, src/r_things.c
This is mostly cleanup, with the exception that polyobject planes should now behave somewhat better than they do in 2.1 currently (translucent polyobj planes should now always be actually translucent regardless of where you view them from, for instance). I can't claim I've fixed their rendering once and for all though, there may still be bugs for all I know...
=> Software plane rendering fixes/cleanup

src/p_mobj.c
Use mobj->watertop instead of mobj->spawnpoint->z. CEZ3 is far from fixed in multiplayer, but this is still one less thing to worry about.
=> One Eggscalibur fix

src/d_clisrv.c, src/d_clisrv.h, src/p_saveg.c, src/p_setup.c, src/p_spec.c, src/r_defs.h
Yes, this another netgame related fix! Named this "savegame hotfixes" rather than "ERCZ hotfix" or the like in advance of the fact we probably need a general branch for other $$$.sav fixes? (for instance I must fix changed sector tags at some point)
Anyway, bugs fixed by this branch:
* ERCZ's lava falls act as expected, fixing all other known desynchronisation issues known in the map for the time being (yay)
=> Savegame hotfixes

src/w_wad.c
After going back over my PMs from the Message Board, I found myself wondering "Why _do_ transmaps cause a game modification, and is there anything I can do to prevent this?"
This was my solution.
Unfortunately its also untested, as I don't have a build environment set up, but judging from the surrounding code, such a fix should work.
I have no idea if this affects netgames in a manner that would cause desyncing.
Note that I /suppose/ that if another lump started with TRANS, say, a texture named TRANSEGG, or TRANS2S8, those might be able to be modified by this, but such a thing would require changes to the other listed names to make this impossible with any of them that its just not feasible.
=> Added transmaps to non modifying lump list.

src/p_map.c
Jumping at spikes on FOFs in reverse gravity - most notably in ERZ3 - no longer teleports you downwards into the death pit beneath it.
=> A spike bug no more

src/r_segs.c
This is a fix for the Lava Mountain freeze issue from TD (KartKrew/TD#13) which can also occur in vanilla SRB2 as it turns out. Basically the issue occurs whenever an FOF with a single-patch texture with holes goes off the bottom of the screen far enough.
=> TD rendering freeze fix

src/d_main.c
This fixes the special console window used by dedicated mode not properly telling the game when shift is held down since the console improvements added in 2.1.17. This means shift+1 is properly interpreted as "!" again rather than 1, shift+- should be "_" rather than "-", etc.
Sorry LJSonic your problems from pre-2.1.17 are probably just your keyboard being for a different locale than the one most SRB2 players play with, I'm not sure what can be done for the time being. =V
Fun note, you can see how the game interprets un-executed input to the console window by playing normal (not dedicated) SRB2 with `-console`, which creates a second window for the console just like you'd see for dedicated mode. Drop down the console on the main SRB2 window, switch to the console window and type …
=> Dedicated console shift-down fix

src/g_game.c
This fixes the bug reported here: http://mb.srb2.org/showthread.php?t=42342
Record Attack now no longer allows the tally to be skipped, whether by custom exits or by Lua etc.
=> Record attack custom exit fix

src/r_things.c
This fixes artifacts of rain/snow sprites appearing on-screen in levels that have rain/snow, if said sprites were high enough above the camera. This kind of thing was previously fixed for sprites of regular objects (and textures of FOFs?), but apparently the fix wasn't applied to sprites for precipitation as it turns out.
I found this most easily reproducable in SRB2TD's Stormy Streets level, because some of the invisible FOFs make raindrops continually splash right up at the sky ceiling itself. Position your camera underneath them right and ...voila, ghostly precip sprites apparently appearing. (You'll need to make a SOC to make the level playable in vanilla SRB2 mind)
=> Precipitation sprite overflow fix

src/m_misc.c
Fix for this bug: https://mb.srb2.org/showthread.php?t=42508
The game should now print an error saying all 10000 slots have been used up. It was already there funnily enough, just someone goofed up in the code for finding the next screenshot name to use.
=> Screenshot slots fix

src/p_spec.c
Fix for https://mb.srb2.org/showthread.php?t=42491
Note that the crash reported occurs only if Lua has been initialized (by having a Lua script loaded) and a LinedefExecute hook function has been added.
=> Linedef type 443 (Call Lua Function) fix

src/v_video.c
made it more consistent with other drawing functions; doesn't draw off of the sides, and doesn't ignore snapping or widths for reasons that don't make sense
(for instance: the green bar in MI's test script showed *above* the blue one in non-green resolutions in 2.1.17)
=> DrawFill made not stupid

src/d_netcmd.c, src/m_menu.c
Fixes "allowteamchange no" to actually work properly and NOT desync you from the game in most cases. You can now switch TO spectator freely (as intended it turns out), and switching FROM spectator is prohibited. The "Enter Game" menu option in Match/Tag now displays one of those blue window notices just like with "Change Teams" in CTF/Team Match if you cannot change teams right now. Everything else works as you'd expect.
The de-sync issue was originally reported here https://mb.srb2.org/showthread.php?p=789965#85
=> Allowteamchange fix

src/d_clisrv.c
Okay, THIS time admin bans should work properly. Turns out the relevant code for banning did not properly consider the case of admins doing the banning, at least until now.
Unlike my last attempt at fixing admin bans (!165), this one would require both host and admin to have the fix exe assuming everyone else would be using 2.1.17, so I'm merging to next instead of master.
=> Admin ban fix

objs/DC/SDL/Debug/.gitignore, objs/DC/SDL/Release/.gitignore, objs/Linux/SDL/Debug/.gitignore, objs/Linux/SDL/Release/.gitignore, objs/Linux64/SDL/Debug/.gitignore, objs/Linux64/SDL/Release/.gitignore, objs/Mingw/Debug/.gitignore, objs/Mingw/Release/.gitignore, objs/Mingw/SDL/Debug/.gitignore, objs/Mingw/SDL/Release/.gitignore, objs/Mingw64/Debug/.gitignore, objs/Mingw64/Release/.gitignore, objs/Mingw64/SDL/Debug/.gitignore, objs/Mingw64/SDL/Release/.gitignore, objs/PS3/SDL/Debug/.gitignore, objs/PS3/SDL/Release/.gitignore, objs/PSP/SDL/Release/.gitignore, objs/SDL/Release/.gitignore, objs/VC/.gitignore, objs/VC9/.gitignore, objs/Wii/SDL/Debug/.gitignore, objs/Wii/SDL/Release/.gitignore, objs/WinCE/SDL/Release/.gitignore, objs/djgppdos/Debug/.gitignore, objs/djgppdos/Release/.gitignore, objs/nds/Debug/.gitignore, objs/nds/Release/.gitignore
Partial backtrack of changes I made in !174. Apparently removing all the `.gitignore` files from `/objs`'s subfolders removed the only reason Git was keeping the folders alive (Git doesn't care about empty folders as it turns out). So now they have `.gitignore`s again, with a warning in each not to remove them
=> obj folders fix

src/d_net.c
Quick hotfix to prevent `Net_CloseConnection` from crashing if the node's number is invalid.
=> Invalid node hotfix master

src/p_enemy.c
Turns out not having MF_SHOOTABLE can cause the Jet Jaw to endlessly loop between the two states, until somehow LUA_CallAction inexplicably causes Z_StrDup to crash anyway (that one's a mystery to me, I'm not going to look into it right now). I tweaked A_JetJawChomp so this endless loop can't happen anymore.
=> Jet Jaw crash fix

src/y_inter.c
Fixes the issue reported here: https://mb.srb2.org/showthread.php?t=42530
What it turns out is going on is that making the game bail out in the middle of Y_StartIntermission if you're a dedicated server's host prevents the game from awarding the players bonuses in coop mode. Therefore it's not just special stage bonuses, but ANY kind of bonuses that can cause desyncs if someone loses all their lives.
This can be merged to master since it's a change only for dedicated server hosts, and should otherwise be compatible with 2.1.18.
=> Dedicated bonuses fix

src/d_netcmd.c
This branch fixes this bug: https://mb.srb2.org/showthread.php?t=41811
Here's an explanation of how this bug is actually happening:
* Pressing Enter with "Start" selected calls `D_MapChange` to make a map change command. (Note that part of it is actually delayed because it's called from a menu, but this isn't relevant to the bug)
* `D_MapChange` itself calls `SV_StartServer` to start up the server, if you're supposed to be the server player.
* Pressing Esc while starting up a server like shown in the gif causes the server to be cancelled, and go back to the title screen.
* HOWEVER, since we're still in `D_MapChange`, the map change command is made anyway.
* Since we're not in a netgame as expected, no random seed is added, and the map change command has a total size of 9 bytes (1 for the …
=> Exit your server desync fix

src/p_mobj.c
This fixes the Egg/Ideya capsule from NiGHTS stages being given SKINCOLOR_RED as a color. Not really relevant for vanilla SRB2 (since it doesn't use green in the sprite), but it may be relevant for custom mods using a custom NiGHTS capsule sprite that happens to use green.
=> NiGHTS capsule color fix

src/p_mobj.c
Fixed that thing where missiles like sliding up slopes for some reason.
This isn't a 1:1 fix compared to non-slopes - missiles still like stepping up over the borders of sloped sectors and will continue going as long as they never touch that ground again, whereas they can never step up on flat ones - but this fixes the most egregrious issue.
=> Missiles 'n slopes

src/d_clisrv.c, src/d_net.c, src/d_netfil.c, src/d_netfil.h
Various netcode fixes are included in this branch. Most important of all of course is a fix for the Net_CloseConnection invalid node -32769 detected message thing, or rather what actually caused that to occur.
It's a merge to master since everything here should be compatible with 2.1.18: the only main changes are related to recieving packets (whether you're the host of a netgame or a client), which AFAIK shouldn't cause desyncs if you played with these fixes on a 2.1.18-hosted netgame (or hosted a netgame with the fixes and 2.1.18-using players join you).
=> Netcode hotfix

src/d_clisrv.c
Turns out PT_ASKINFOVIAMS is an obsolete packet type anyway, the MS doesn't send it at all. So let's just ignore it in the netcode then. (the online page just acts like a client and sends PT_ASKINFO, and is not part of the MS itself)
=> Ignore askinfoviams

src/g_game.c, src/g_game.h
This fixes how changes to the player's scale are recorded in Record Attack demos, so ghosts of your demos don't disappear when they attempt to change to scales >= FRACUNIT (if they didn't change scales at all they were unaffected).
Have some gifs for comparison:
* A demo recorded without the fix:
* A demo recorded with the fix:
=> Record Attack ghosts scale fix

src/hardware/hw_main.c, src/r_bsp.c
This fixes both Software and OpenGL renderers so that polyobject segs aren't drawn if the game is drawing the actual subsectors they're from (outside the main level, where the polyobject walls were pre-spawn). They should only appear as part of the polyobject itself in-level.
This means a few glitches with polyobjects are probably fixed: for instance in Software mode, polyobject walls sometimes appear through level boundaries (and make everything above/below vanish, turning into HOM or skybox), if the BSP rendering code happens to find one of the subsectors said segs came from outside the level. I don't think anything similar happens in OpenGL, though I'm sure some unwanted typecasting is happening as a result of attempting to draw the segs. (And it fixes a crash in 2.2 anyway.)
=> Polyobject seg render fix

src/d_clisrv.c
Somehow, the part of the netcode for calculating the players' pings in a netgame frequently gets the concepts of nodes and players mixed up, which is probably not a good thing. This branch of course fixes those slipups.
I originally based this branch on master to be merged to it (since it only fixed issues on the host's side), but after finding another issue with clients receiving PT_PING from the server, I decided to make this a merge to next instead.
=> Ping-related code fix

src/g_game.c
This fixes how functions for the "PlayerSpawn" Lua hook aren't called when the player respawns at a starpost instead of at a map thing start.
(Note to Lua scripters who may want to adjust their scripts accordingly with this in future, checking if `player.starposttime` is non-zero is the best way to detect if you're spawning at a starpost or not.)
=> Fix for Lua's "PlayerSpawn" hook

src/hardware/hw_main.c
This fixes some issues with sloped FOFs that affect lighting in OpenGL (as in, those that cast a shadow or have a colormap). Particularly, they can do strange things to any wall textures adjacent to them, as we've noticed ourselves in levels for 2.2. =P
=> OpenGL slope FOF lighting fix

src/p_map.c
The issue was that because both them and the player had MF_SOLID, the tmfloorz of the spring was getting set to above the player (or vicea versa with tmceilingz), forcing it upwards with them under certain circumstances.
Now, springs only acknowledge the solidity (for purpose of tmfloorz/tmceilingz) of objects they CAN'T launch.
=> No more jumping springs FOR REAL!

src/lua_script.c
This fixes some potential problems with archiving mobjinfo_t/state_t data via Lua in netgames (whether as custom mobj/player vars or by NetVars hook). Thanks to LJSonic for pointing this out to me.
=> Lua archive value fix

src/y_inter.c
* The TIME/SCORE part of the HUD now doesn't move from the position it was before the tally screen started in non-green resolutions. The example screenshots of this bug and the fix for it below are all taken in 640x480:
How it should be:
How it displays in 2.1.19:
How it displays in an exe with the fix:
* The time display at the tally screen no longer limits the minute number to between 0 and 59.
How a time > 60 mins displays normally just before finishing the level:
How it displays afterwards (it's supposed to be 61:19 but it's wrapped to 1:19 instead):
=> Sp tally non green res hud fix

src/d_clisrv.c
Don't kick Tails! Also, a movement for the WRITESINT8 to prevent modification to buf if the function bails early.
This can go into Master, right? It only matters for the host, and it's explicitly only having a major effect outside of netgames.
=> Pwease no kicky

src/p_spec.c
Apparently when I made `P_RunTriggerSpecial` less than 3 years ago (August 2014) and cleaned up the trigger linedef code, I accidentally inverted the ability check for linedef types 305-307 by mistake, thereby causing the linedefs to activate for anyone EXCEPT those with the ability instead. Whoops.
=> Charability trigger hotfix

src/p_map.c
This fixes P_FloorzAtPos not considering the normal floor slope of the sector the given x/y/z coord is in, if one is set. Though apparently it already did consider FOF slopes, huh.
=> P_FloorzAtPos slope fix

src/lua_script.c
Turns out that it's possible to cause Lua to panic by setting a function, thread or light userdata (or otherwise unrecognised data type) as a table's key. When the server tries to write one of these data types to the $$$.sav for someone joining the netgame, these are instead written as nil type. At the other end, for the person joining the netgame, a "LUA PANIC" crash occurs because of a table key being nil when fed into lua_rawset (a function that actually sets table[key] = value for a particular table).
Now, you just get a bunch of console errors for both the server and joiners, to alert both somebody goofed up a Lua script by using any of those unaccepted key types. (Or perhaps corrupted the savegame) But the game should run fine otherwise, not crash.
=> Hotfix for "LUA PANIC" crash when joining a netgame

src/d_clisrv.c
If a PT_SERVERTICS packet contains net commands already executed, do not allocate them again, as they would never be freed afterward.
Note that along with wasting memory, not freeing net commands could also continuously decrease performance as you stayed on a server, because the game often needs to iterate through the net command list, which would grow more and grow with time.
=> Fix net commands not always being freed

src/dehacked.c
Hopefully fixes the crash reported in this post here: [Crash Reports (SIGSEGVs, etc) #132
](https://mb.srb2.org/showthread.php?p=799012#post799012)
The crash occurred because of the game iterating over a line of text from a "Frame" aka "State" SOC block for seemingly no purpose whatsoever: if it had no '=' or a new line char on the end (such as when you set the Action for a state), it presumably then went outside the buffer thus causing access violations. Fun.
=> SOC sanitizing

src/sdl/i_system.c
This branch fixes `I_GetFreeMem` always returning 48 MB for Linux 32-bit versions of SRB2.
It turns out that the `LINUX` macro was never defined by Makefiles when compiling for that specific port (except in the NASM files, apparently).
=> Linux limbo

src/d_clisrv.c
Fixes [SRB2MB: [Linux]Filename is truncated on download screen](https://mb.srb2.org/showthread.php?t=42904). Turns out the full path name (with DOWNLOAD/ or [home]/DOWNLOAD/) was being truncated, THEN what's left of the actual file name in the truncated name was used of that. That's just silly, all we need to care about is the actual file name itself.
I also improved the behaviour for extremely long filenames (even without the path) - ellipsis is now used in the middle to shorten the name, as seen below:
(the full name was abcdefghijklmnopqrstuvwxyz1234567890.wad, just so you know :) )
=> Download filename trunc fix

src/lua_script.c
GetUserdataArchType was always working with the value on top of the stack, which caused it to work with the table values instead of the table keys.
=> Fix Lua panic when archiving a table element with an userdata key

src/d_main.c
This fixes a bug discovered by Steel Titanium, in which passing both `-server` and `-connect` will cause the game to hang on the startup screen.  This is due to the fact that `-server` takes precedence over `-connect`, but cannot preform a map change because `-connect` is one of the parameters.
=> Removed contradictory `-connect` check

src/d_main.c, src/sdl/sdl_sound.c
Apprently on dedicated servers, SRB2 will still init the sound system, wasting memory by caching the level music into RAM. There is also a very low chance the level music could play for a split second as soon the dedicated server is up.
=> Don't init the sound system on dedicated servers

src/m_menu.c
Fixes [SRB2MB: Playername max length is different between console/player setup menu](https://mb.srb2.org/showthread.php?t=43519). Turns out the menu was at fault in this case.
This is a merge to master since I'm pretty sure this doesn't affect netplay directly
=> Multiplayer menu playername fix

src/d_main.c, src/d_netcmd.c
SRB2 sets a random admin password if you don't set one yourself, but since the PRNG seed is initialised using the OS time, the password is extremely easy to figure out.
Who would want a random password anyway.
=> Disable admin password by default

src/lua_consolelib.c
Fix the host crashing if they recieved Lua commands when they shouldn't be able to recieve Lua commands.
=> Lua exploit fix

src/hardware/hw_md2.c
Originally fixed by toaster. Fixes a case where animations can end up being jerky(like FSonic's Super Sonic walk animations) In her own words[:"The jerkiness was caused by treating all calculations as if interpoleration should be within the bounds, whilst not actually doing anything to limit it to that"](https://mb.srb2.org/showpost.php?p=798298&postcount=69) Should be safe to merge to master.
=> Smoother MD2 interpolation

src/hardware/hw_md2.c
Now when fopen() fails to open md2.dat, it will get the last error and print it to the console, instead of letting the user having to figure out what the error is.
=> More helpful error messages

src/hardware/hw_main.c
This fixes an OpenGL renderer crash derrek encountered while testing his recent 3DS port. Also a little code cleanup I guess.
=> OpenGL HWR_ProjectSprite fix

src/hardware/hw_main.c
For FOFs, Lower Unpegged flag on in-level sectors (or control sector for transfer line FOFs) is supposed to change pegging to "attach" itself to the FOF's bottom instead of the top. Unfortunately, it seems OpenGL was missing this feature... at least until now, of course.
Sorry in advance Lat!
=> OpenGL: FOF walls + Lower unpegged

src/d_netcmd.c
Hotfix for LJSonic's password security fix: prevent 
> Password from [player name] failed (no password set)
from being printed in the console for everyone that's not the host if someone tries to use the verify command, regardless of whether a password is actually set or not.
=> Password fix hotfix

src/lua_script.c
This now means:
* Lua strings longer than 1024 chars can now be read properly without awful crashes
* Lua strings with embedded zeros can be written/read without truncating anything (hopefully)
=> Rewrite archiving/unarchiving of Lua strings for netgames.

src/r_draw8.c
Change the order of operations when applying transparency and colormap such that colormap isn't applied to the screen pixel twice (or, in the case of R_DrawTranslatedTranslucentColumn_8, thrice). The issue manifests itself as transparent, non-fullbright objects being unusually dark.
Please note I haven't touched the ASM equivalents, given as they're not actually used.
This doesn't mark a return to vanilla development; rather, this is something I discovered while I was bugfixing for Kart, and figured vanilla had right of first refusal on.
This merge request is set to go into master because it is purely visual.
=> Transparency? I hardly knew 'er!

src/lua_maplib.c
Accessing a sector_t's floorpic or ceilingpic should now works properly; you should no longer get hidden`\0` chars messing up checks like `if sector.ceilingpic == "F_SKY1"`, nor trimming everything after the string in a printed message like in `print(sector.floorpic.." is the floor flat for this sector")`.
=> Lua sector names fix

src/r_data.c, src/r_plane.c, src/r_things.c
Continuing my recent streak of making random lighting/colormap-related fixes to long-standing bugs:
* Fix that thing where ALL transparent FOF planes were continuously fullbright unless encased in a fog which disables sprite fullbrightness, which was long-hated by many people in the community!
* For backwards compatibility, setting flag 1 in that fog field (which is probably the most common "in-the-wild" usage of this feature) will continue to make objects un-fullbright.
* For situations where you desperately want the fullbright plane behaviour to be enabled, you can apply fog flag 2.
* Change the fadestart and fadeend range in which colormaps are generated.
* The problem HERE was that the darkest light level reached by generated colormaps was actually slightly brighter than the darkest …
=> Lighting fixes? Plane and simple!

src/v_video.c
Clean up a bunch of v_video.c functions that previously exhibited unfortunate side effects when run in non-green resolutions.
* V_DrawFixedPatch and ilk:
* Change the offset of V_FLIP so it's not one screen-pixel off where its non-flipped sprite would have started being drawn from.
* Write to x and y as well as desttop so that anti-screen-overflow checks later in the function behave properly with non-green resolutions.
* V_DrawFill:
* Reduce number of operations performed upon `c`.
* V_DrawString and ilk:
* Offset the left and right boundary checks in non-green resolutions such that you can actually draw stuff to the left of basevid screen x coordinate 0.
=> v_video Killed The r_radio Star

src/p_setup.c, src/r_data.c, src/r_data.h
If anyone ever looked into the code that is used to create colormaps from linedef type 606, they'll know that there are in fact *two* functions that do mostly the same thing: `R_CreateColormap`, which is called first for each sidedef with the colormap special, and then `R_CreateColormap2` which is called afterwards via `R_MakeColormaps` and redoes *everything* the first function did (with the addition of some extra stuff needed for software mode).
It turns out `R_CreateColormap2` (and therefore `R_MakeColormaps` as well) is entirely unnecessary! I have therefore removed said function(s), and adding anything exclusive to it to `R_CreateColormap`.
This should hopefully make the colormap generation code a lot saner for SRB2 coders to understand now. Hopefully there should be no visible …
=> Colormap code cleanup

src/Makefile, src/sdl/mixer_sound.c, src/win32/win_snd.c
Split zlib stuff from libpng, removing the hard dependency on libpng to decompress VGZ lumps, also uncommented lines that was commented out in sdl/mixer_sound.c, for whatever reason. If someone compiles without zlib, then PNG support will be explicitly disabled also.
=> Makefile: Split zlib and libpng

src/lua_script.c, src/w_wad.c
* Fix a memory leak regarding implementation of SOC_ (improperly copypasted code from LUA_LoadLump!!)
* Optimise the repeated strlen usage into a single call, which is stored for later.
Special thanks to Sryder for discovery of the original issue.
=> Free SOC_s to a good home

src/r_data.c
If you didn't know, apparently SRB2 was hardcoded to double the height of 64x64 textures created using TX_START/TX_END. This has frustrated some a lot. This branch removes this hack at last (there doesn't appear to be any visual issues resulting from removing it, anyway).
Backport from 2.2.
=> No doubling texture heights plz

src/m_anigif.c
From [More accurate GIF delay by PrisimaTheFox](https://github.com/STJr/SRB2/pull/284) on GitHub:
```
This change makes the GIF frame delay much more accurate. It was changed from a fixed 3, which caused the GIF to be inaccurate by 1 tic every 7 tics when the TICRATE was 35.
```
I remade the branch on this repo to fix the commit mess on the original. Credit goes to Prisima for doing this obviously
=> More accurate GIF delay

src/android/i_sound.c, src/djgppdos/i_sound.c, src/dummy/i_sound.c, src/i_sound.h, src/nds/i_sound.c, src/s_sound.c, src/sdl/mixer_sound.c, src/sdl/sdl_sound.c, src/sdl12/mixer_sound.c, src/sdl12/sdl_sound.c, src/win32/win_snd.c, src/win32ce/win_snd.c
I've voided this out on other sound interfaces than SDL Mixer ones because I'm both not sure whether they need it, and not sure how to make them work with it if they do.
I chose this option over the other 2 because the first I was fairly sure would possibly still have the issue, and the other I felt would still present issues from the possibility of clearing the channels in one thread while another is doing stuff with them... If the channel code in s_sound could be made thread safe somehow it could potentially be possible?
See [#33](https://git.magicalgirl.moe/STJr/SRB2/issues/33).
=> Handle fix for SDL Mixer

src/f_finale.c, src/g_game.c, src/g_game.h, src/y_inter.c, src/y_inter.h
This is mostly just some code cleanup and moving about:
* `Y_EndGame` was moved from from y_inter.c/h to g_game.c/h, and renamed to `G_EndGame`. Frankly the old place that function lived didn't make sense, since it has nothing to do with tally screens directly.
* Most of `Y_FollowIntermission`'s code was removed, because `G_AfterIntermission` does it all already.
* And lastly, `G_ExitLevel` uses `HU_ClearCEcho()` instead of `HU_CEcho("")` to clear CEchos from the screen.
The only visible changes in-game from the above should be just that log.txt stops adding empty new lines when you complete a level, and CEchos will always be cleared after tally screens when a level goes to credits/evaluation next.
(Backport from 2.2)
=> Endgame code refactor

src/android/i_sound.c, src/d_main.c, src/d_netcmd.c, src/djgppdos/i_sound.c, src/doomstat.h, src/dummy/i_sound.c, src/hardware/hw3sound.c, src/i_sound.h, src/m_menu.c, src/p_mobj.c, src/s_sound.c, src/s_sound.h, src/sdl/i_video.c, src/sdl/mixer_sound.c, src/sdl/sdl_sound.c, src/win32/win_cd.c, src/win32/win_main.c, src/win32/win_snd.c
The music code was a freaking mess because it had different methods for digital and MIDI playback; redundant variables; and unclear separation for loading, playing, stopping, and unloading.
This is all internal plumbing, no user-facing changes (other than small sound menu tweaks.) Nothing that affects netsync because audio is not shared.
* I combined all digital/MIDI methods
* `nomidimusic nodigimusic nosound` are merged into the existing variables `midi_disabled digital_disabled sound_disabled`
* I separated `S_Init` into `S_InitSfxChannels`
* I clearly separated playback and loading concerns
* Internally, loading and playing a song are now called separately (`S_ChangeMusic` calls both)
* Currently, stopping a song will also auto-unload it. I have plans to change this so that multiple …
=> Music Code Cleanup

src/r_draw.h, src/r_draw8.c, src/r_segs.c, src/screen.c, src/screen.h
Adds a column drawer to software renderer to support multi-patch textures for midtextures on two-sided linedefs with both transparency (i.e. invisible pixels) and translucency (set by linedef types 900-908). Before, you would have just gotten tutti-frutti or whatever it's called.
This was originally coded for 2.2, but I'm backporting it since I don't see any real reason to keep it back.
=> Multi-patch texture support for transparency AND translucency

src/d_netcmd.h, src/g_game.h, src/g_input.h, src/m_misc.h
Just moving the locations of some consvar externs from d_netcmd.h to other header files in which I think they should REALLY belong. Ultimately this should not affect gameplay whatsoever, it's just code cleanup.
Another backport of commits I made for 2.2.
=> MI minor refactoring

src/hardware/hw_draw.c, src/v_video.c
It turns out that V_NOSCALESTART is dumb and breaks patch left/top offset scaling unless V_OFFSET is also set ...but V_OFFSET itself doesn't support V_FLIP, bleh.
So, what I have done in the following branch is:
* Fix V_OFFSET for now so that it supports V_FLIP.
* Make sure V_OFFSET does nothing without V_NOSCALESTART, as otherwise it might do strange things to your patch's position I expect.
I eventually plan to kill V_OFFSET and put in its place a more useful flag for 2.2, most likely a vertical version of V_FLIP (wouldn't that be great). This merge request is the first step in making that happen, you could say.
=> Patch offsets fix

src/lua_hudlib.c
Adds simple Lua functions that can probably go a long way... more or less:
*  hud.enabled(huditem) will return true or false depending on if huditem is enabled or disabled, which will DEFINITELY help mods using huds not look out of place when another mod decides to disable huds for misc purposes.
*  v.getLocalTransFlag() is a way more situational, it returns V_HUDTRANS as a regular V_xxTRANS flag, which means that people can work from that transparency to get consistent results with the player's settings.
=> Lua: hud.enabled and v.getLocalTransFlag()

src/w_wad.c
Fixes [SRB2MB: Executing a TXT a lot makes the game no longer saves your config/data](https://mb.srb2.org/showthread.php?t=43687).
Turns out that when you attempt to add a file that's already loaded, the game forgets to close its handle. This means that if you add the file enough times you actually hit the limit for how many files you can have open eventually. The MB's thread way is just one way of getting this quickly it turns out; another one found by Steel is just having many lines of adding the same file redundantly in the text file, where you only need to run it once before you get the same bug.
=> File loading hotfix

src/dehacked.c
This fixes crashes that can occur in SOCs if you accidentally put in lines with no = within certain SOC blocks (such as if you accidentally "merge" two blocks together by forgetting to put a newline between, or you forgot to put in the "=" for certain parameters).
Merging to next in case of downloading files that cause those with regular 2.1.20 to crash, just like the original "SOC sanitising" branch + MR.
=> SOC sanitising the sequel!

src/p_mobj.c
When WRITETHINGS, all NiGHTS Bumper vertical angles were reset because their flag values were being fudged after mobj spawn. Don't do this!
Backported from 2.2.
=> Objectplace: Fix NiGHTS bumper angle being reset when WRITETHINGS

src/d_main.c, src/hardware/hw_bsp.c, src/hardware/hw_data.h, src/hardware/hw_drv.h, src/hardware/hw_main.c, src/hardware/hw_md2.c, src/hardware/hw_md2.h, src/hardware/hw_trick.c, src/p_setup.c, src/r_defs.h
Partial backport of some cleanup and fixes I made in the OpenGL code for 2.2, there may or may not be more to come. Among other things, I've cleaned up hw_md2.c and hw_trick.c
As for fixes, `gr_correcttricks on` should no longer break flats on slopes. We had that happen in 2.2's GFZ2 if you've been reading the commit descriptions, lol.
EDIT: Also backported the pv1/pv2 pointers I created for seg rendering in OpenGL. Here if my original description of pv1/pv2 addition from the internal MR I made:
>  hw_bsp.c's `AdjustSegs` no longer assigns polyvertex_t (OpenGL's own kind of vertex for rendering purposes) data to v1/v2 of segs directly, but new pointers pv1/pv2 for polyvertex_t data specifically. These pv1/pv2 pointers are then used everywhere for OpenGL's seg rendering instead of v1/v2. …
=> Opengl improvements backport

src/byteptr.h, src/d_main.c, src/d_main.h, src/dehacked.c, src/doomtype.h, src/f_finale.c, src/f_finale.h, src/hu_stuff.h, src/p_mobj.h, src/r_plane.h, src/r_splats.h, src/screen.c, src/sdl/i_cdmus.c, src/sdl/i_system.c, src/sdl/i_video.c, src/sdl/mixer_sound.c, src/sdl/sdl_sound.c, src/sdl12/sdl_sound.c, src/st_stuff.h
Mostly just cleaning up stuff to do with preprocessor directives and macros, for the benefit of those trying to compile the game. This started off as fixes for GCC 8 (mostly to do with `FUNCMATH`), but includes other general technical stuff such as checking for endianness in some files.
=> Compiling cleanup and fixes

SRB2.cbp, src/CMakeLists.txt, src/Makefile, src/doomdef.h, src/hardware/hw_clip.c, src/hardware/hw_clip.h, src/hardware/hw_main.c, src/r_bsp.c, src/r_bsp.h
Backport of 2.2's new clipping code for OpenGL.
Original description from the internal MR I made for this (along with the changes in the now-merged OpenGL improvements branch):
>  **EXPERIMENTAL NEW CLIPPING CODE** - this is the thing I need people to check out in particular. I have made efforts to port SRB2CB's clipping code, which is in turn from PrBoom+, in order to try and improve the speed of OpenGL rendering. While I am not sure if I succeeded in doing this, this also fixes rendering glitches with translucent walls (such as the waterfall at the start of GFZ1).
=> OpenGL new clipping backport

src/p_floor.c
See [SRB2MB: The Deathly Monitors II: The Ghostly, Jumpy, Occasionally Sticky Monitors](https://mb.srb2.org/showthread.php?t=39784) for some context.
I found out three years ago that the cause of the first issue in the thread was a combination of several things: a fix I made once to fix solid objects suddenly warping on top of another, and the little-known fact that the monitor actually is just *slightly* above the FOF itself at the end of the bob. Apparently at some point during those three years physics of solid objects were changed again, fixing the intangibility part... but not the latter technicality.
This branch fixes objects on floating, bobbing FOFs so that they are *definitely* on top of the FOF at the very end of a bob. This would have fixed the thread's first issue even if it …
=> Fix for object z positions on floating, bobbing FOFs

src/sdl/IMG_xpm.c
This made VC fail building.
The XPM declarations:
```c
#if 0
#include "SDL_image.h"
#else
extern SDLCALL int SDLCALL IMG_isXPM(SDL_RWops *src);
extern SDLCALL SDL_Surface *IMG_LoadXPM_RW(SDL_RWops *src);
extern SDLCALL SDL_Surface * SDLCALL IMG_ReadXPMFromArray(const char **xpm);
#define IMG_SetError    SDL_SetError
#define IMG_GetError    SDL_GetError
#endif
```
SDLCALL defines:
```c
/* By default SDL uses the C calling convention */
#ifndef SDLCALL
#if (defined(__WIN32__) || defined(__WINRT__)) && !defined(__GNUC__)
#define SDLCALL __cdecl
#elif defined(__OS2__) || defined(__EMX__)
#define SDLCALL _System
#else
#define SDLCALL
#endif
#endif /* SDLCALL */
```
SDLCALL expands to nothing on GCC, but expands to `__cdecl` in VC, which threw that compiler off.
It's not necessary because we're …
=> Remove unnecessary SDLCALL from IMG_xpm.c declarations

src/hardware/hw_draw.c, src/screen.c
This fixes OpenGL's HUD not placing the Score/Time/Rings stats, as well as other HUD items such as the Race countdown numbers + GO graphics, in the right places on screen in non-green resolutions, compared to Software mode.
Have some images for comparison (both taken in 640x480): 
Before fix:
After fix:
I also probably fixed an issue with HUD items using V_SNAPTO* flags combined with the scaling flags, but I haven't tested this out properly yet.
=> OpenGL HUD scaling fix

src/p_setup.c
…era has an initial subsector set!I've lost track how often I've seen crash reports that lead back to `P_CameraCheckWater` or perhaps `P_CameraCheckHeat`, almost always seeming to be a crash accessing the camera's subsector.
Naturally I've gotten tired of these kind of crashes, so I've attempted a fix for it now. Basically, I've made sure the camera should have a subsector set initially when a level is loaded. If this by some mad chance doesn't fix the crashes, I still think the game should have been doing this anyway in the level loading code, so whatever. \*shrugs\*
This is a fix for master, because the camera is always a local thing in the first place.
=> Camera subsector crash fix

assets/.gitignore, assets/LICENSE-3RD-PARTY.txt, assets/LICENSE.txt, assets/README.txt
This adds a readme and license text to package with installs, to satisfy the requirements of applying GPL to the code.
Our libraries' licenses need to be included with our installs. They are copy-pasta'd one after the other in a single file, LICENSE-3RD-PARTY.TXT. [I'm following the practice here](https://softwareengineering.stackexchange.com/questions/234511/what-is-the-best-practice-for-arranging-third-party-library-licenses-paperwork).
**Can someone please go through all our libraries and add their licenses to this text? It should be sufficient just to go through the libs folder, but also mind SRB2DD's libraries too, like FMOD.**
Note that for SDL Mixer, you also need to go into `libs/SDL2_mixer/i686(...)/bin` and get the licenses for FLAC, Vorbis, and other codecs.
See the …
=> WIP: Add README and LICENSE for installs [HELP WANTED]

src/m_fixed.h
gcc accepts
__asm__ ( "" : : : "%cc");
but not clang:
error: unknown register name '%cc' in asm
:"%cc", "%edx"         // edx and condition codes clobbered
'cc' is not a register, thus '%cc' is rightfully not accepted.
Repro: build the project on x86_64 with:
cmake -H. -Bbuild -DCMAKE_C_COMPILER=clang -DCMAKE_SIZEOF_VOID_P=4 -DCMAKE_C_FLAGS="-m32"
=> m_fixed: asm: cc is not a register

src/info.c
This branch fixes the skybox disappearing after using objectplace command. The fix is really simple, but it works!
=> Objectplace skybox fix.

src/d_netcmd.c, src/hardware/hw_bsp.c, src/hardware/hw_glob.h
hw_bsp.c:
```c
// Is this really necessary at this point..?
V_DrawCenteredString(BASEVIDWIDTH/2, 40, V_YELLOWMAP, "OPENGL MODE IS INCOMPLETE AND MAY");
V_DrawCenteredString(BASEVIDWIDTH/2, 50, V_YELLOWMAP, "NOT DISPLAY SOME SURFACES.");
V_DrawCenteredString(BASEVIDWIDTH/2, 70, V_YELLOWMAP, "USE AT SONIC'S RISK.");
```
~~*No, no it's not.*~~
But really. OpenGL hasn't been shown to crash any computers, and we do "kind of" support it. I think the loading screen is due for removal.
This also hides the console slightly earlier in the map change routine, because in OpenGL, switching maps in-console would still display the console for a split second. With the fix, the loading display is now clean and consistent with software.
=> Hide OpenGL loading screen

src/p_map.c
Backported from 2.2.
Prior, if drone is on inverted axis, player could break lap detection (which dictates hoop/ring respawn during bonus time) just by U-turning. `player->anotherflyangle` breaks in this case. 
[Example GIF](https://i.imgur.com/eORSzVR.gif)
Fixed by using `player->flyangle` instead. No ill effects, works as expected in both regular and inverted axis types.
See [here](https://mb.srb2.org/showthread.php?t=43304) for discussion.
Due to using `flyangle`, this also changes the angle comparison slightly (`> 90 && < 270` instead of `>= 90 && <= 270`) to account for the edge case where flying directly up (`flyangle 90`) or directly down (`flyangle 270`) is registered as a BACKWARDS loop, not a FORWARDS loop. So if you `JUMPTOAXIS` out of drone while flyangle 90 or 270, you could …
=> NiGHTS fix lap detection on inverted axis

src/command.c, src/d_clisrv.c, src/d_clisrv.h, src/d_netcmd.c, src/d_netcmd.h, src/dehacked.c, src/doomstat.h, src/f_finale.c, src/hu_stuff.c, src/lua_baselib.c, src/lua_consolelib.c, src/m_menu.c, src/r_things.c, src/sdl/Srb2SDL-vc10.vcxproj
Does exactly what it says: allows more than one admin to be active at a time. Comes with a few changes as a result:
*  `verify` has been renamed to `promote`
*  A new command called `demote` has been added, which can be used to remove admin privileges
*  The `admin` global variable in Lua now points to the first entry in the `adminplayers` array for backwards compatibility reasons. 
* `IsPlayerAdmin()` has been exposed to Lua. In the future, this function should be used for any and all admin checking in Lua.
I made a few mistakes during the backport (since this junk is over a year old) so a review would be appreciated. I think I fixed everything, but I wouldn't be surprised if something slipped past me.
=> Multiadmin backport

SRB2.cbp, src/CMakeLists.txt, src/blua/Makefile.cfg, src/lua_blockmaplib.c, src/lua_libs.h, src/lua_script.c, src/sdl/Srb2SDL-vc10.vcxproj, src/sdl/Srb2SDL-vc10.vcxproj.filters, src/win32/Srb2win-vc10.vcxproj, src/win32/Srb2win-vc10.vcxproj.filters
I have added a new Blockmap search library! (with a new file: lua_blockmaplib.c)
* Format of iteration function: `searchBlockmap(searchtype, function, mobj, [x1, x2, y1, y2])`. Returns true if search was uninteruppted, false if the iteration function returned true or false at any point
* *searchtype* can be either "objects" or "lines", for looking for mobj_t and line_t stuff in the blockmap respectively
* *function* is a function of your choice to iterate with:
- format of function needed: `funcname(mobj, foundmobj)` or `funcname(mobj, foundline)` (for searching for objects and lines, respectively)
- return value of *function* affects searching somewhat: nil doesn't change searching, false ends searching in a block (but doesn't stop searching, it just moves onto the next), and true ends …
=> Lua: Blockmap search library backport

src/d_clisrv.c, src/g_game.c, src/m_menu.c
* Menu: Map Joy 2 to menu back (escape)
* Menu: Map Joy 3 to control clear (backspace)
* Make M_Responder operate on `(ev->type == ev_keydown)` for joy/mouse inputs ONLY IF (menuactive) because joy/mouse buttons were triggering menu-specific keys in-game
* Change joystick axis defaults to 360-friendly values
* Move with Left Stick; Camera with Right Stick; Ring Toss with Left Trigger; Normal Toss with Right Trigger
* Tie joystick vertical look to `cv_alwaysfreelook` and `cv_chasefreelook` (for next)
* Add joystick vertical look toggle to menu
Based on next because of M_Responder quirk fix and `cv_chasefreelook`
=> Joystick additions for menu, axis defaults, and vertical look toggle

src/d_netcmd.c
This just changes `use_joystick` and `use_joystick2`'s default values from zero to 1 and 2, respectively. Kart does the same thing. This would allow the user to start using a joystick without having to go into the settings. 
Putting this up just to make sure there are no objections on principle.
=> Use Joystick 1 and Joystick 2 by default if plugged in

src/dehacked.c
…r copying timeattackfolderFixes the weird [savegame name path string issue](https://git.magicalgirl.moe/STJr/SRB2/uploads/e051de2db3a1369db520772b17bdf8d2/srb20028.png). All happens in `dehacked.c`, which overwrites the default SRB2 save path. Facts:
1. `timeattackname` is the game mod name truncated to 64 chars, so this is safe to append to `savegamename`
2. When overwriting `savegamename`, the old code used `strncpy(..., ..., strlen(timeattackname)`. This copies the whole of `timeattackname`, but NOT the null char
* Therefore, if the previous `savegamename` was `C:\Users\MarcoZ\SRB2\srb2sav%u.ssg`, the new string becomes `sugoiers\MarcoZ\SRB2\srb2sav%u.ssg`. **THIS IS THE FAILURE POINT!**
3. When appending the `%u.ssg` piece, that's appended to the end of the OLD string
* …
=> Fix savegamename being improperly built

src/p_mobj.c, src/p_user.c
This fixes the `P_CameraCheckWater` crash encountered in Acidic Alpines in Kimokawaiii, and possibly a few similar scenarios. Turns out that Acidic Alpines uses a MT_THOK awayviewmobj for some reason, which eventually is removed from the map (leading to the crash).
The problem is really just that the game never really considered an alt view cam mobj that gets removed when in use. =P
=> Awayviewmobj sanity checks

src/command.c, src/d_net.c, src/m_misc.c
`srb2home` was missing from EXEC, SAVECONFIG, and debugfile, so those commands would look in the improper folders for Mac and Linux (and Windows, if `%userprofile%\SRB2` was being used. To test, move config.cfg to that path.)
Tests well with `srb2home` set to SRB2 install path as well as user profile folder.
It's worth noting that file finding is a MESS in the current code, and not at all centralized... I'm *pretty* sure these three cases are the only ones not already handled with `srb2home`.
=> Apply srb2home path to EXEC, SAVECONFIG, and debugfile

src/sdl/mixer_sound.c, src/sdl/sdl_sound.c
This fixes the sound pitch bugs described in [!373](https://git.magicalgirl.moe/STJr/SRB2/merge_requests/373). 
Context: SDL 2.0.6 switched to using WASAPI, which expects sound samples to be 32-bit floating point. We don't do that conversion in our sample handling, so this env var hack forces the old DirectSound driver.
It would be *better* to actually fix the sample handling, but this one-liner is quick and easy. I'm unaware of what benefits we would lose by doing this, because this is basically what the game was using before, with the 2.0.3 DLL.
=> SDL: Force use DirectSound driver to fix wrong-pitch sound effects

src/dehacked.c, src/doomstat.h, src/lua_maplib.c, src/p_setup.c
Kind of like how 2.2 works, but has a default option for compat w/ 2.1
=> Feature: Save override for level header

src/hardware/hw_main.c
Closes #43; fixes z-fighting for sprites with dispoffset in OpenGL. Even fixes for FOF (cutsprites). Thanks Azeonus!
=> OpenGL z-fighting fix [by Azeonus]

src/d_clisrv.h
I discovered this function existed in the C standard library fairly recently. ...so I thought why not try it out where we ought to be using it?
This is based on `next` in case of any potential side effects that could affect netplay, given the only places I'm using the function atm are in netcode related areas of the source.
=> Use the `offsetof` function

src/g_game.c, src/p_setup.c, src/p_user.c
- Very slightly less claustrophobic camera defaults
- Changed camera settings are saved
- Camera distance increases relatively with splitscreen & analog mode.
These changes are kind of debatable because them not saving was an intentional decision before 2.2, and the camera being farther out could potentially clip more geometry where it previously didn't... still, thought I'd open this for consideration; it makes me less nauseous personally, and I'm pretty sick of mashing a bind every time I die. :V
Correct me if I'm wrong, but this should change the default even without adding to the cool config updater, because the cvars didn't have CV_SAVE before.
=> Suggestion: 2.2 camera changes backport

src/Makefile.cfg, src/command.c, src/hardware/hw_bsp.c, src/hardware/hw_draw.c, src/hardware/hw_main.c, src/hardware/r_opengl/r_opengl.c, src/r_data.c, src/sdl/mixer_sound.c, src/win32/win_vid.c
Abuse `fpclassify` and `fabsf` to avoid directly compare floating numbers
=> Clear Float equal warnings

src/sdl/i_video.c
Use `SDL_WINDOWPOS_CENTERED_DISPLAY(n)`, which is really the macro behind `SDL_WINDOWPOS_CENTERED`.
Guesstimation, pending testing.
=> Center window on current monitor during vidmode change

src/p_user.c
Fixes [#49](https://git.magicalgirl.moe/STJr/SRB2/issues/49). It turns out it's nothing to do with ultimate mode at all, but everything to do with the respawning-after-death code and how bots can apparently trigger it anyway if you get a GAME OVER. You have 0 lives, but the bot doesn't lose lives, you see.
=> Bot respawn fix

src/r_data.c
Welp, looks like we got our first regression from !375...
This code block compares a proposed colormap's `maskamt`, a double, to the list of existing colormaps' `maskamt`. If there's a match, then don't create a new colormap.
The old check failed in 32-bit release builds because the returned delta was greater than the compare value `1.0-E36`. This resulted in more colormaps being created than necessary -- in one case, crashing DSZ2 for exceeding `MAXCOLORMAPS`.
I thought about changing the comparison value, but then I figured that we don't need to cast `maskamt - extracolormaps[i].maskamt` to float when it's already a double.
So I just changed the comparison to a `double` and it now works. Tested in 32-bit release and debug builds; and 64-bit release and debug builds.
On another note, it …
=> Fix float comparison for colormap maskamt

src/Makefile, src/win32/Makefile.cfg
Revision of [!438 ](https://git.magicalgirl.moe/STJr/SRB2/merge_requests/438)
Per discussion, `-march=nocona` is only set when `X86_64=1`. `LINUX64=1` does not set this flag. 
`MINGW64=1` *does* currently set this flag, but only because we assume x86-64 in `src/win32/makefile.cfg`. If we stop assuming x86-64 in the future, then `X86_64` should not be set by `MINGW64` at that time.
`M5` is also renamed to `ARCHOPTS` and can be overridden by command line.
=> MinGW64:Target nocona for 64-bit builds [revision]

src/w_wad.c
With this, HUD and font WADs will no longer trigger WAD downloading from servers.
Since this was brought up in `addons-backport`, I may as well drop this here. Let the upvotes decide on inclusion. Pulled straight from 2.2.
=> Expand NMUSList to include HUD changes

src/s_sound.c, src/s_sound.h, src/sdl/mixer_sound.c
All: A limiter was applied so the music don't get disorted with certain formats. Add missing MUS_FLAC case to the switch statement.
libopenmpt: Only call ```openmpt_module_set_repeat_count(mod, -1)`` if ``looping`` is set. Move openmpt_module_set_render_param out of the mix hook and into I_PlaySong and modfilter cvar, so it can apply on song playback and cvar value change.
=> Some few changes to libopenmpt branch

src/m_misc.c
Since supposedly the current code *can't* work with newer versions of libpng that have the apng patch, it won't compile if that's what people have.
It seems like some Linux distros are adding the apng patch to libpng and that'll make things annoying to compile for people.
I think it goes without saying, but if there's ever a fix to make newer libpng versions work with the APNG code then this can be reverted.
=> Disable the APNG code if the version of libpng is greater than 1.4.

src/r_segs.c
Cherry picked from Kart. Original description by colette:
>A small patchover for Jimita's polyobject fixes. This should resolve HOMs on planes above/below polyobjects that render with upper/lower (respectively) textures, and shouldn't impact the original
=> Fix rendering gaps on polys with upper/lower textures

src/p_user.c
Fixed the Tails bot not respawning after death. This was because of an oversight of mine made when I made the fix in [423](https://git.magicalgirl.moe/STJr/SRB2/merge_requests/423) last year; I thought Tails's respawn checking code ran when he was dead, but apparently not!
=> Tails bot dead forever fix

src/console.c, src/d_main.c, src/hu_stuff.c, src/sdl/i_video.c
This should prevent modifier keys from getting 'stuck'. I don't know exactly how modifiers come to be stuck. But I've experienced it on multiple occasions. I've also seen reports of shift becoming stuck--mistaken for caps lock--becoming difficult to deduce.
=> Set modifiers in a non-reactive manner

libs/libgme.props, src/sdl/Srb2SDL-vc10.vcxproj, src/sdl/Srb2SDL.props, src/win32/Srb2win-vc10.vcxproj, src/win32/Srb2win.props
MSVC builds did not have GME enabled, so I fixed that up real quick.
This flips on `HAVE_LIBGME` and `HAVE_ZLIB` for SRB2WIN and SRB2DD. It compiles and works fine on Visual Studio 2015 (target platform 8.1)
[r_opengl.dll](https://git.magicalgirl.moe/uploads/a6aeaea6031c78a7ea965f4fb89b863b/r_opengl.dll)
[fmodexL.dll](https://git.magicalgirl.moe/uploads/cbbca40488023a5d2410c3e9c23831c1/fmodexL.dll)
[Srb2DD-gme.exe](https://git.magicalgirl.moe/uploads/deba9af48b5274544d9d29c7f1bae5ea/Srb2DD-gme.exe)
[Srb2Win-gme.exe](https://git.magicalgirl.moe/uploads/f3bde246b0a77a6592184ac37d85d986/Srb2Win-gme.exe)
[test_music.wad](https://git.magicalgirl.moe/uploads/b71a697b56bd756e29cb2cc9fb70563a/test_music.wad) (`tunes gme01`)
=> Add GME to MSVC 10 solution

src/Makefile.cfg
Hi.
Had some trouble compiling in Linux due to GCC version being too recent.
Problem were a few tab characters causing Makefile.cfg from parsing successfully and stopping the build pre-emptively.  
This fix substitutes spaces for those tabs.
=> Use spaces instead of tabs in Makefile.cfg
